-- auto-generated definition
create table works_translate_task
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp with time zone default now() not null,
    updated_at      timestamp with time zone default now() not null,
    uid             varchar,
    origin_language varchar,
    status          varchar
);

comment on table works_translate_task is 'works_translate_task';

comment on column works_translate_task.id is '自增id';

comment on column works_translate_task.created_at is '创建时间';

comment on column works_translate_task.updated_at is '更新时间';

comment on column works_translate_task.uid is 'uid';

comment on column works_translate_task.origin_language is 'origin_language';

comment on column works_translate_task.status is 'status: 0未翻译，1已翻译';
